### ISSUE TITLE
EXCEL转对象时，时间类型报错

### ISSUE THREAD

**Issue by xinxiuqiangwei** [jptangchina/jxcel#3]
现象：EXCEL中有一个录入时间，当用户没有填写此时间进行导入时后台转对象会报错。
期望：如果不填，日期对象为空

**Comment by jptangchina** [comment]
非常感谢你的issue，问题已经修复
但是当前版本还存在诸多的不足，具体我已经写在了README中，还烦请了解下

**Comment by xinxiuqiangwei** [comment]
好的，目前正在使用easyExcel，继续努力(•̀ᴗ•́)و



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jptangchina"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月7日(星期天) 中午12:32
收件人:&nbsp;"jptangchina/jxcel"<jxcel@noreply.github.com&gt;;
抄送:&nbsp;" "<wathui@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jptangchina/jxcel] EXCEL转对象时，时间类型报错 (#3)





 
非常感谢你的issue，问题已经修复
 但是当前版本还存在诸多的不足，具体我已经写在了README中，还烦请了解下
